"use client";

import { useState, useCallback, useMemo } from "react";
import type {
  DataCard,
  DataDashboardConfig,
  CardLayout,
  SchemaResponse,
} from "./types";

const STORAGE_KEY_PREFIX = "data-explorer-dash-";
/** Bump this when layout generation changes to invalidate stale localStorage configs */
const LAYOUT_VERSION = 5;

function genId() {
  return `dc_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
}

/* ─── Auto-generate a default dashboard from schema ──────────── */
export function autoGenerateDashboard(
  source: string,
  groupId: string,
  schema: SchemaResponse,
): DataDashboardConfig {
  const cards: DataCard[] = [];
  const layouts: CardLayout[] = [];

  const numericCols = schema.schema.filter(
    (c) =>
      c.type === "integer" ||
      c.type === "decimal" ||
      c.type === "numeric" ||
      c.type === "number",
  );
  const hasLineage =
    schema.schema.some((c) => c.name === "NamedPnlName") &&
    schema.schema.some((c) => c.name === "MasterBookID");

  // Row 0: KPI tiles (up to 4 numeric columns)
  const kpiCols = numericCols.slice(0, 4);
  kpiCols.forEach((col, i) => {
    const id = genId();
    cards.push({
      id,
      type: "kpi",
      label: `Avg ${col.name}`,
      kpiConfig: {
        column: col.name,
        operation: "avg",
        color: ["#2563EB", "#7C3AED", "#059669", "#D97706"][i] ?? "#2563EB",
      },
    });
    layouts.push({ i: id, x: i * 3, y: 0, w: 3, h: 2, minW: 2, minH: 2 });
  });

  // If fewer than 4 KPIs, add a count tile
  if (kpiCols.length < 4) {
    const id = genId();
    cards.push({
      id,
      type: "kpi",
      label: "Total Records",
      kpiConfig: {
        column: schema.schema[0]?.name ?? "",
        operation: "count",
        color: "#2563EB",
      },
    });
    layouts.push({
      i: id,
      x: kpiCols.length * 3,
      y: 0,
      w: 3,
      h: 2,
      minW: 2,
      minH: 2,
    });
  }

  // Row 1: Chart card (full width)
  const chartId = genId();
  cards.push({
    id: chartId,
    type: "chart",
    label: "Chart",
    chartConfig: {},
  });
  layouts.push({ i: chartId, x: 0, y: 2, w: 12, h: 7, minW: 4, minH: 4 });

  // Row 2: Summary (half) + Table (half) — same height, side by side
  // Summary height adapts to number of KPI tiles (3-col grid: ceil((count+1)/3) rows)
  const kpiCount = Math.min(numericCols.length, 6) + 1; // +1 for "Total Records"
  const kpiRows = Math.ceil(kpiCount / 3);
  // Each KPI row ≈ 3 grid units (tile height ~100px at rowHeight=40) + 1 for header
  const summaryH = Math.max(4, kpiRows * 3 + 1);

  const summaryId = genId();
  cards.push({ id: summaryId, type: "summary", label: "Summary Metrics" });
  layouts.push({
    i: summaryId,
    x: 0,
    y: 9,
    w: 5,
    h: summaryH,
    minW: 4,
    minH: 3,
  });

  const tableId = genId();
  cards.push({
    id: tableId,
    type: "table",
    label: "Data Table",
    tableConfig: { pageSize: 25 },
  });
  // Table matches summary height, minimum 7 for enough rows
  const tableH = Math.max(7, summaryH);
  layouts.push({ i: tableId, x: 5, y: 9, w: 7, h: tableH, minW: 5, minH: 4 });

  // Row 3: Lineage (if applicable)
  if (hasLineage) {
    const lineageId = genId();
    cards.push({
      id: lineageId,
      type: "lineage",
      label: "Lineage Flow",
      lineageConfig: {},
    });
    layouts.push({
      i: lineageId,
      x: 0,
      y: 20,
      w: 12,
      h: 8,
      minW: 8,
      minH: 4,
    });
  }

  return {
    id: `dash_${source}`,
    name: `${source} Dashboard`,
    source,
    groupId,
    cards,
    layouts,
    globalFilters: {},
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    layoutVersion: LAYOUT_VERSION,
  };
}

/* ─── Hook ───────────────────────────────────────────────────── */
export function useDataDashboard(source: string, groupId: string) {
  const [config, setConfig] = useState<DataDashboardConfig | null>(null);
  /** Snapshot of what's persisted in localStorage — used for dirty-checking */
  const [lastSavedConfig, setLastSavedConfig] = useState<string | null>(null);

  const storageKey = `${STORAGE_KEY_PREFIX}${source}`;

  /** Compare in-memory config against last persisted snapshot */
  const isDirty = useMemo(
    () =>
      config !== null &&
      lastSavedConfig !== null &&
      JSON.stringify(config) !== lastSavedConfig,
    [config, lastSavedConfig],
  );

  // Load from localStorage (rejects stale layout versions)
  const loadDashboard = useCallback((): DataDashboardConfig | null => {
    try {
      const raw = localStorage.getItem(storageKey);
      if (raw) {
        const parsed = JSON.parse(raw) as DataDashboardConfig;
        if (parsed.layoutVersion !== LAYOUT_VERSION) {
          localStorage.removeItem(storageKey);
          return null;
        }
        setConfig(parsed);
        setLastSavedConfig(JSON.stringify(parsed));
        return parsed;
      }
    } catch {
      // ignore parse errors
    }
    return null;
  }, [storageKey]);

  /** Update in-memory config only (no localStorage write) */
  const updateConfig = useCallback((cfg: DataDashboardConfig) => {
    const updated = { ...cfg, updatedAt: new Date().toISOString() };
    setConfig(updated);
  }, []);

  /** Write current config to localStorage */
  const persistDashboard = useCallback(() => {
    if (!config) return;
    const snapshot = JSON.stringify(config);
    try {
      localStorage.setItem(storageKey, snapshot);
    } catch {
      // storage full — ignore
    }
    setLastSavedConfig(snapshot);
  }, [config, storageKey]);

  /** Revert in-memory config to last persisted version */
  const revertDashboard = useCallback(() => {
    if (!lastSavedConfig) return;
    try {
      const reverted = JSON.parse(lastSavedConfig) as DataDashboardConfig;
      setConfig(reverted);
    } catch {
      // ignore
    }
  }, [lastSavedConfig]);

  // Initialize with auto-generated or loaded config
  const initDashboard = useCallback(
    (schema: SchemaResponse) => {
      const existing = loadDashboard();
      if (existing) return existing;
      const generated = autoGenerateDashboard(source, groupId, schema);
      // Auto-persist initial generation
      const snapshot = JSON.stringify(generated);
      setConfig(generated);
      setLastSavedConfig(snapshot);
      try {
        localStorage.setItem(storageKey, snapshot);
      } catch {
        // storage full
      }
      return generated;
    },
    [source, groupId, loadDashboard, storageKey],
  );

  // Card CRUD — all use updateConfig (in-memory only)
  const addCard = useCallback(
    (card: DataCard, layout: CardLayout) => {
      if (!config) return;
      updateConfig({
        ...config,
        cards: [...config.cards, card],
        layouts: [...config.layouts, layout],
      });
    },
    [config, updateConfig],
  );

  const updateCard = useCallback(
    (cardId: string, partial: Partial<DataCard>) => {
      if (!config) return;
      updateConfig({
        ...config,
        cards: config.cards.map((c) =>
          c.id === cardId ? { ...c, ...partial } : c,
        ),
      });
    },
    [config, updateConfig],
  );

  const removeCard = useCallback(
    (cardId: string) => {
      if (!config) return;
      updateConfig({
        ...config,
        cards: config.cards.filter((c) => c.id !== cardId),
        layouts: config.layouts.filter((l) => l.i !== cardId),
      });
    },
    [config, updateConfig],
  );

  const updateLayouts = useCallback(
    (layouts: CardLayout[]) => {
      if (!config) return;
      updateConfig({ ...config, layouts });
    },
    [config, updateConfig],
  );

  const updateGlobalFilters = useCallback(
    (filters: Record<string, string>) => {
      if (!config) return;
      updateConfig({ ...config, globalFilters: filters });
    },
    [config, updateConfig],
  );

  const resetDashboard = useCallback(() => {
    try {
      localStorage.removeItem(storageKey);
    } catch {
      // ignore
    }
    setConfig(null);
    setLastSavedConfig(null);
  }, [storageKey]);

  const moveCard = useCallback(
    (cardId: string, dir: -1 | 1) => {
      if (!config) return;
      const idx = config.cards.findIndex((c) => c.id === cardId);
      const target = idx + dir;
      if (idx < 0 || target < 0 || target >= config.cards.length) return;

      const newCards = [...config.cards];
      [newCards[idx], newCards[target]] = [newCards[target], newCards[idx]];

      const cardAId = config.cards[idx].id;
      const cardBId = config.cards[target].id;
      const layoutA = config.layouts.find((l) => l.i === cardAId);
      const layoutB = config.layouts.find((l) => l.i === cardBId);
      const newLayouts = config.layouts.map((l) => {
        if (l.i === cardAId && layoutB)
          return { ...l, x: layoutB.x, y: layoutB.y };
        if (l.i === cardBId && layoutA)
          return { ...l, x: layoutA.x, y: layoutA.y };
        return l;
      });

      updateConfig({ ...config, cards: newCards, layouts: newLayouts });
    },
    [config, updateConfig],
  );

  const moveCardPosition = useCallback(
    (cardId: string, dx: number, dy: number) => {
      if (!config) return;
      const newLayouts = config.layouts.map((l) => {
        if (l.i !== cardId) return l;
        const newX = Math.max(0, Math.min(12 - l.w, l.x + dx));
        const newY = Math.max(0, l.y + dy);
        return { ...l, x: newX, y: newY };
      });
      updateConfig({ ...config, layouts: newLayouts });
    },
    [config, updateConfig],
  );

  const resizeCardWidth = useCallback(
    (cardId: string, dw: number) => {
      if (!config) return;
      const newLayouts = config.layouts.map((l) => {
        if (l.i !== cardId) return l;
        const newW = Math.max(l.minW ?? 2, Math.min(12, l.w + dw));
        const newX = Math.min(l.x, 12 - newW);
        return { ...l, w: newW, x: Math.max(0, newX) };
      });
      updateConfig({ ...config, layouts: newLayouts });
    },
    [config, updateConfig],
  );

  return {
    config,
    setConfig,
    isDirty,
    initDashboard,
    persistDashboard,
    revertDashboard,
    loadDashboard,
    addCard,
    updateCard,
    removeCard,
    moveCard,
    moveCardPosition,
    resizeCardWidth,
    updateLayouts,
    updateGlobalFilters,
    resetDashboard,
  };
}
